---
ID: "0fbfd0c1-695a-4b48-a9eb-9fe386be9079"
Parent: "9c4c36b7-f63a-4a3f-a19b-fd071212a6dc"
Template: "d2a6884c-04d5-4089-a64e-d27ca9d68d4c"
Path: /sitecore/content/Financial/BECU/Presentation/Placeholder Settings/Partial Design/Product Content
SharedFields:
- ID: "7256bdab-1fd2-49dd-b205-cb4873d2917c"
  Hint: Placeholder Key
  Value: "sxa-landing-page-content"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "067750a8-d565-4502-9907-862af85e63ea"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260414T235851Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\allen.blanton@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\allen.blanton@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a2964e51-585d-4f88-bf80-008e6ff29c1b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\allen.blanton@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260415T000812Z
