---
ID: "d4afe806-f3f1-4f81-92e7-08c318e4bd8a"
Parent: "175a5b0f-a181-446d-a0ea-4b8f5ee42db2"
Template: "175a5b0f-a181-446d-a0ea-4b8f5ee42db2"
Path: /sitecore/templates/Project/Financial/Components/Rendering Parameters/Article List/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260415T011216Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "151f10ab-b32e-4814-9b74-e7dd79bf48b1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\NCmpg1NJNoisu0v2Hkl2W4WbpXbnkjY3
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260415T011216Z
